### ISSUE TITLE
Arrange food, drink, and venue access for Refresh OKC event | 2017-07-26

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/user-groups#356]
What: Introduction to the WordPress Rest API
When: 07/26/2017 11:30 am
Where: 1141 W Sheridan Ave, Oklahoma City

Check meetup for RSVP count: https://www.meetup.com/Refresh-OKC/events/241090784/

For @matthewreily:
- [x] Order delivery unless you have written confirmation from a UG leader that they will pick up the order
- [x] Post picture of order here. Please include pickup time and location or delivery time if not included in image

For the UG leadership (@RicksConcepts @susansimkins):
Please follow up with the following:
 - [ ] Picture of receipt(s)
 - [ ] Final head count
 - [ ] Photo of meetup in action
 - [ ] Any food or food service feedback (was it on time, how much was left over, was the service adequate, etc)

**Comment by matthewreily** [comment]
![screen shot 2017-07-26 at 7 06 46 am](https://user-images.githubusercontent.com/8399844/28620069-05ea89aa-71d1-11e7-8618-c71d8e35a4e1.png)
![screen shot 2017-07-26 at 7 07 56 am](https://user-images.githubusercontent.com/8399844/28620113-28511298-71d1-11e7-9ff7-b6923cb8f7a4.png)

**Comment by RicksConcepts** [comment]
**Tasks**
- Roughly 15 people in attendance 
- Dominoes was about 5 minutes late but that was alright. I would like to request that we have no more than 5 Pizzas ordered. We typically go through 3-4 pizzas and having 1 as a buffer I think would be just fine. If we do have an influx for that meet up then we'll stick to the first come first served idea. Thank you!
- See pictures for receipt and meetup info.

![wordpress-rest-api-intro-7](https://user-images.githubusercontent.com/6116624/28782775-cdfbe33e-75d3-11e7-9110-5fa3c1861736.jpg)
![20170726_113108](https://user-images.githubusercontent.com/6116624/28782774-cdf6baee-75d3-11e7-998d-ea0b2a4be01f.jpg)

**Comment by RicksConcepts** [comment]
@seejessicacode
